<?php

namespace Solutions\Reply24\Classes;

class TileType
{
    public static function getTypes(): array
    {
        return [
            'F' => new Direction(
                leftRight: true,
                rightLeft: true,
                leftDown: true,
                downLeft: true,
                leftUp: true,
                upLeft: true,
                upDown: true,
                downUp: true,
                upRight: true,
                rightUp: true,
                downRight: true,
                rightDown: true,
            ),
            'E' => new Direction(
                leftRight: false,
                rightLeft: false,
                leftDown: true,
                downLeft: true,
                leftUp: true,
                upLeft: true,
                upDown: true,
                downUp: true,
                upRight: false,
                rightUp: false,
                downRight: false,
                rightDown: false,
            ),
            'D' => new Direction(
                leftRight: false,
                rightLeft: false,
                leftDown: false,
                downLeft: false,
                leftUp: false,
                upLeft: false,
                upDown: true,
                downUp: true,
                upRight: true,
                rightUp: true,
                downRight: true,
                rightDown: true,
            ),
            'C3' => new Direction(
                leftRight: true,
                rightLeft: true,
                leftDown: false,
                downLeft: false,
                leftUp: false,
                upLeft: false,
                upDown: true,
                downUp: true,
                upRight: false,
                rightUp: false,
                downRight: false,
                rightDown: false,
            ),
            'C' => new Direction(
                leftRight: false,
                rightLeft: false,
                leftDown: false,
                downLeft: false,
                leftUp: false,
                upLeft: false,
                upDown: true,
                downUp: true,
                upRight: false,
                rightUp: false,
                downRight: false,
                rightDown: false,
            ),
            'B' => new Direction(
                leftRight: true,
                rightLeft: true,
                leftDown: false,
                downLeft: false,
                leftUp: true,
                upLeft: true,
                upDown: false,
                downUp: false,
                upRight: true,
                rightUp: true,
                downRight: false,
                rightDown: false,
            ),
            'A5' => new Direction(
                leftRight: false,
                rightLeft: false,
                leftDown: false,
                downLeft: false,
                leftUp: true,
                upLeft: true,
                upDown: false,
                downUp: false,
                upRight: false,
                rightUp: false,
                downRight: true,
                rightDown: true,
            ),
            'A' => new Direction(
                leftRight: false,
                rightLeft: false,
                leftDown: false,
                downLeft: false,
                leftUp: true,
                upLeft: true,
                upDown: false,
                downUp: false,
                upRight: false,
                rightUp: false,
                downRight: false,
                rightDown: false,
            ),
            '96' => new Direction(
                leftRight: false,
                rightLeft: false,
                leftDown: true,
                downLeft: true,
                leftUp: false,
                upLeft: false,
                upDown: false,
                downUp: false,
                upRight: true,
                rightUp: true,
                downRight: false,
                rightDown: false,
            ),
            '9' => new Direction(
                leftRight: false,
                rightLeft: false,
                leftDown: false,
                downLeft: false,
                leftUp: false,
                upLeft: false,
                upDown: false,
                downUp: false,
                upRight: true,
                rightUp: true,
                downRight: false,
                rightDown: false,
            ),
            '7' => new Direction(
                leftRight: true,
                rightLeft: true,
                leftDown: true,
                downLeft: true,
                leftUp: false,
                upLeft: false,
                upDown: false,
                downUp: false,
                upRight: false,
                rightUp: false,
                downRight: true,
                rightDown: true,
            ),
            '6' => new Direction(
                leftRight: false,
                rightLeft: false,
                leftDown: true,
                downLeft: true,
                leftUp: false,
                upLeft: false,
                upDown: false,
                downUp: false,
                upRight: false,
                rightUp: false,
                downRight: false,
                rightDown: false,
            ),
            '5' => new Direction(
                leftRight: false,
                rightLeft: false,
                leftDown: false,
                downLeft: false,
                leftUp: false,
                upLeft: false,
                upDown: false,
                downUp: false,
                upRight: false,
                rightUp: false,
                downRight: true,
                rightDown: true,
            ),
            '3' => new Direction(
                leftRight: true,
                rightLeft: true,
                leftDown: false,
                downLeft: false,
                leftUp: false,
                upLeft: false,
                upDown: false,
                downUp: false,
                upRight: false,
                rightUp: false,
                downRight: false,
                rightDown: false,
            ),
        ];
    }
}
